name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Checkout other repor
        uses: actions/checkout@v2
        with:
          repository: shankybnl/MobileAutomationFramework
          
      - name: MVN build
        run: |
          cat ./testng.xml
          MVN clean
          
